apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - primary/configmap.yaml
  - primary/statefulset.yaml
  - primary/svc-headless.yaml
  - primary/svc.yaml
  - secrets.yaml
  - serviceaccount.yaml