replicaCount: 2

image: 
  repository: luciarp10/learningkubernetes.example.io
  tag: "3.6"

readinessProbe:
  httpGet:
    path: /
    port: 3000

livenessProbe: 
  httpGet: 
    path: /
    port: 3000

service: 
  type: ClusterIP
  internalPort: 3000

env: 
- name: HOST_BD
  value: "mysql-headless"
- name: PORT_BD
  value: "3306"
- name: USER_BD
  value: "admin"
- name: PASS_BD
  value: "devel"
- name: NAME_BD
  value: "books"