---
# Source: nodejs/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-nodejs
  labels:
    app: nodejs
    chart: nodejs-0.1.1
    release: release-name
    heritage: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
      release: release-name
  template:
    metadata:
      labels:
        app: nodejs
        release: release-name
      annotations:
        {}
    spec:
      containers:
        - name: nodejs
          image: "nmolnar/learningkubernetes.example.io:3.0"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: HOST_BD
              value: 172.17.0.3
          envFrom:
            []
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - containerPort: 9999
              name: prometheus
              protocol: TCP
          resources:
            {}
